### ISSUE TITLE
How to detect compatible board?

### ISSUE THREAD

**Issue by and7ey** [pauln/esphome-linp-doorbell-g04#5]
Looks like there is no clear instructions how to detect which board is compatible with this firmware (and when the previous firmware should be used) 

Here is my board
![IMG_20230528_114622_edit_73718225584063](https://github.com/pauln/esphome-linp-doorbell-g04/assets/900474/5fecfef0-efe4-4352-a60a-b831b4c3c483)

Can it be used with this firmware?

**Comment by pauln** [comment]
My boards are v1.0 (as seen in https://github.com/pauln/esphome-linp-doorbell-g03/issues/23) - but I think v1.1 should also be compatible with this firmware (as far as I can tell, https://github.com/pauln/esphome-linp-doorbell-g03/issues/22 was a v1.1 and I didn't hear of any compatibility issues after releasing this component).

I'd suggest taking a backup of the original firmware before flashing, so that you have something to revert to if this component doesn't work on your board.  Please feel free to open a new issue here if the component doesn't work on your board; if that happens, please include a photo of the other side of the board, with the chip numbers visible (or list the chip numbers in the issue description if you can't get a clear photo of them).
